name: Azure AD B2C Policy Upload

on:
  push:
    branches:
      - main

jobs:
  install-and-upload:
    runs-on: windows-latest  # Use a Windows runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your repository code to access the PowerShell script

      - name: Install the module
        shell: pwsh
        run: |
             Install-Module -Name AzureADPreview -Scope CurrentUser -Force -AllowClobber

      - name: Import the module
        shell: pwsh
        run: |
             Import-Module AzureADPreview

      - name: Install the module
        shell: powershell
        run: |
             Install-Module -Name AzureAD -Scope CurrentUser -Force -AllowClobber

      - name: Import the module
        shell: powershell
        run: |
             Import-Module AzureAD


      - name: Connect the module
        shell: pwsh
        run: |
             Connect-AzureAD
