name: Azure AD B2C Policy Upload

on:
  push:
    branches:
      - main

jobs:
  install-and-upload:
    runs-on: windows-latest  # Use a Windows runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your repository code to access the PowerShell script

      - name: Install Microsoft.Graph.Entra.Beta module
        shell: pwsh
        run: |
          Install-Module -Name Microsoft.Graph.Entra.Beta -AllowPrerelease
          
      - name: Import the module
       shell: pwsh
        run: |
          Import-Module Microsoft.Graph.Entra.Beta
