name: Azure AD B2C Policy Upload

on:
  push:
    branches:
      - main

jobs:
  install-and-upload:
    runs-on: windows-latest  # Use a Windows runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your repository code to access the PowerShell script

      - name: Azure login
        run: |
          # Log in to Azure using the service principal credentials directly
          az login --service-principal --username "d6fc48d7-cc9b-4aa2-bea2-fa02c83fc376" --password "YT_8Q~SDJV0gXTBxtxhTLtwPGf.B69PBzKyVhc-B" --tenant "a0cea021-2598-436f-93f0-502a2e82b10c" --allow-no-subscriptions

          # Get the access token for Microsoft Graph API
          access_token=$(az account get-access-token --resource-type ms-graph --query accessToken -o tsv | tr -d '\r')

          # Define the path to your policy file
          policy_file="B2C_1A_TESTPOLICY.xml"

          # Upload the policy file to Azure AD B2C
          az rest --method post \
            --uri "https://graph.microsoft.com/beta/trustFramework/policies" \
            --headers "Content-Type=application/xml" "Authorization=Bearer $access_token" \
            --body "@$policy_file"
        shell: bash
